//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CybersecurityEducational
{
    public partial class Account
    {
        protected System.Web.UI.WebControls.Panel RegistrationPanel;
        protected System.Web.UI.WebControls.Label RegisterMessage;
        protected System.Web.UI.WebControls.TextBox regUsername;
        protected System.Web.UI.WebControls.TextBox regEmail;
        protected System.Web.UI.WebControls.TextBox regPassword;
        protected System.Web.UI.WebControls.TextBox regConfirmPassword;
        protected System.Web.UI.WebControls.Button RegisterButton;

        protected System.Web.UI.WebControls.Panel LoginPanel;
        protected System.Web.UI.WebControls.Label LoginMessage;
        protected System.Web.UI.WebControls.TextBox loginEmail;
        protected System.Web.UI.WebControls.TextBox loginPassword;
        protected System.Web.UI.WebControls.Button LoginButton;

        protected System.Web.UI.WebControls.Panel twoFactorDemo;
        protected System.Web.UI.WebControls.TextBox verificationCode;
        protected System.Web.UI.WebControls.Button Verify2FAButton;

        protected System.Web.UI.WebControls.Panel PaymentPanel;
        protected System.Web.UI.WebControls.Label PaymentMessage;
        protected System.Web.UI.WebControls.TextBox cardName;
        protected System.Web.UI.WebControls.TextBox cardNumber;
        protected System.Web.UI.WebControls.TextBox expiryMonth;
        protected System.Web.UI.WebControls.TextBox expiryYear;
        protected System.Web.UI.WebControls.TextBox cvv;
        protected System.Web.UI.WebControls.Button SavePaymentButton;
    }
}